---
title: "Composition Model Selection"
author: "Michael Burns"
date: "11/20/2019"
output: html_document
---

```{r loading_packages}
library(dplyr)
library(lme4)
library(ggplot2)
library(caret)
library(ez)
```

```{r loading_data}
cook_comp_data<-read.csv("/Users/michael/Desktop/Grad_School/Research/Datasets/Machine Learning/Kernel_Comp_Cook_Clean.csv")
cook_comp_data$Moisture_Avg<-cook_comp_data$Moisture_Avg*100
cook_comp_data$na<-1
head(cook_comp_data)
```

```{r}
for(i in 5:9){
  png(filename = paste("cooking_variables_", names(cook_comp_data[i]), "_corr_vis.png"))
  print(ggplot(data = cook_comp_data)+
    geom_point(aes(x=cook_comp_data[,i], y=Moisture_Avg))+
    geom_smooth(aes(x=cook_comp_data[,i], y=Moisture_Avg),method = "lm")+
    xlab(names(cook_comp_data[i])))
  dev.off()
}
```
None of the traits seem to have any sort of relationship with the moisture uptake.  Perhaps take more extreme samples would help with this?

```{r}
mavg_mod<-lm(Moisture_Avg~Protein_As_is+Starch_As_is+Fiber_As_is+Fat_As_is+Ash_As_is + Protein_As_is:Starch_As_is+Starch_As_is:Fiber_As_is+Starch_As_is:Fat_As_is+Ash_As_is:Protein_As_is+Ash_As_is:Starch_As_is+Ash_As_is:Fiber_As_is+Protein_As_is:Fiber_As_is+Protein_As_is:Fat_As_is, data = cook_comp_data)
AIC(mavg_mod)
step(mavg_mod, direction = "both") #AIC
#Theres a discrepancy between the AIC values found below and step AIC values.

#step(mavg_mod, direction = "both", k = log(length(cook_comp_data[,1]))) #BIC
```

To determine percent variance explained:
```{r}
best_mod<-lm(formula = Moisture_Avg ~ Protein_As_is + Starch_As_is + Fiber_As_is + 
    Fat_As_is + Ash_As_is + Starch_As_is:Fat_As_is + Starch_As_is:Ash_As_is + 
    Protein_As_is:Fiber_As_is, data = cook_comp_data)
anova(best_mod)
summary(best_mod)
```




___
___
___
```{r proof_of_concept}
AIC(mavg_mod)
AIC(lm(Moisture_Avg~Protein_As_is, data = cook_comp_data))
AIC(lm(Moisture_Avg~Fat_As_is, data = cook_comp_data))
AIC(lm(Moisture_Avg~Fat_As_is+na+na+1+1, data = cook_comp_data))
AIC(lm(Moisture_Avg~Fat_As_is+Starch_As_is, data = cook_comp_data))
AIC(lm(Moisture_Avg~na, data = cook_comp_data))
AIC(lm(Moisture_Avg~1, data = cook_comp_data))


```

```{r}
comp_matrix<-matrix(nrow = 2, ncol = 5)
colnames(comp_matrix)<-c('Protein_As_is','Fat_As_is','Fiber_As_is','Ash_As_is','Starch_As_is')
comp_matrix[1,]<-0
comp_matrix[2,]<-1
comp_matrix

mod_comb<-expand.grid(comp_matrix[,1],comp_matrix[,2],comp_matrix[,3],comp_matrix[,4],comp_matrix[,5])
names(mod_comb)<-colnames(comp_matrix)
for(c in 1:5){
  for(r in 1:32){
    if(mod_comb[r,c]==0){
      mod_comb[r,c]<-names(mod_comb[c])
    }else{mod_comb[r,c]<-"na"}
  }
}
mod_comb
```

```{r}
mod_aic_vect<-vector(length = 32)
for(i in 1:32){
  mod_aic_vect[i]<-AIC(lm(cook_comp_data$Moisture_Avg~
                 cook_comp_data[,mod_comb[i,1]]+
                 cook_comp_data[,mod_comb[i,2]]+
                 cook_comp_data[,mod_comb[i,3]]+
                 cook_comp_data[,mod_comb[i,4]]+
                 cook_comp_data[,mod_comb[i,5]]))
}
selection_vect<-which(mod_aic_vect<(min(mod_aic_vect)+20)) #Very loose selection, should be +5 to 10
best_mods_matrix<-matrix(nrow = length(selection_vect), ncol = 6)
best_mods_df<-data.frame(best_mods_matrix)
best_mods_df[,1]<-mod_aic_vect[selection_vect]
best_mods_df[,2:6]<-mod_comb[selection_vect,]
names(best_mods_df)<-c('AIC','Protein','Fat','Fiber','Ash','Starch')
best_mods_df
```

